services:
  postgres-e2e:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 1s
      retries: 5

  migrations-e2e:
    image: oven/bun:1.2.13-alpine
    entrypoint: ['/bin/ash', '/usr/src/migrations/entrypoint.sh']
    working_dir: /usr/src/migrations
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-e2e:5432/postgres
    volumes:
      - ./docker/migrations/entrypoint.sh:/usr/src/migrations/entrypoint.sh
      - ./drizzle:/usr/src/migrations/drizzle
      - ./drizzle.config.ts:/usr/src/migrations/drizzle.config.ts
    depends_on:
      postgres-e2e:
        condition: service_healthy
